create table dce_events(session_id varchar(50),
client_ip varchar(25),
country varchar(25),
customer_id varchar(25),
device varchar(20),
progress int,
realm varchar(10),
started_at timestamp,
ta varchar(10),
town varchar(25),
ts timestamp,
video_id int,
action int);
