package com.diceplatform.brain

object ActionType {
  val ADMIN_SUSPEND = "ADMIN_SUSPEND"

  val EVENT_ADDED_TO_FAVOURITES = "EVENT_ADDED_TO_FAVOURITES"
  val EVENT_ADDED_TO_WATCH_HISTORY = "EVENT_ADDED_TO_WATCH_HISTORY"
  val EVENT_REMOVED_FROM_FAVOURITE = "EVENT_REMOVED_FROM_FAVOURITE"
  val EVENT_WENT_LIVE = "EVENT_WENT_LIVE"
  val EVENT_WENT_NOTLIVE = "EVENT_WENT_NOTLIVE"

  val LIVESTREAMING_EVENT_UPDATED = "LIVESTREAMING_EVENT_UPDATED"

  val NEW_PLAYLIST_FROM_DVE = "NEW_PLAYLIST_FROM_DVE"
  val NEW_VOD_FROM_DVE = "NEW_VOD_FROM_DVE"

  val REFRESH_TOKEN = "REFRESH_TOKEN"
  val REGISTER_USER = "REGISTER_USER"

  val RESET_PASSWORD = "RESET_PASSWORD"
  val RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"

  val UPDATED_PLAYLIST = "UPDATED_PLAYLIST"
  val UPDATED_VOD = "UPDATED_VOD"

  val USER_ASKED_FOR_EVENT_STREAM = "USER_ASKED_FOR_EVENT_STREAM"
  val USER_ASKED_FOR_MISSING_EVENT = "USER_ASKED_FOR_MISSING_EVENT"
  val USER_ASKED_FOR_MISSING_VOD = "USER_ASKED_FOR_MISSING_VOD"
  val USER_ASKED_FOR_VOD = "USER_ASKED_FOR_VOD"
  val USER_ASKED_FOR_VOD_STREAM = "USER_ASKED_FOR_VOD_STREAM"

  val VOD_ADDED_TO_FAVOURITES = "VOD_ADDED_TO_FAVOURITES"
  val VOD_ADDED_TO_WATCHED = "VOD_ADDED_TO_WATCHED"
  val VOD_REMOVED_FROM_FAVOURITE = "VOD_REMOVED_FROM_FAVOURITE"

  val PLAYLIST_RELATED_VIDEO = "PLAYLIST_RELATED_VIDEO"

  val NOK = "NOK"
  val OK = "OK"

  val FAILED_LOGIN = "FAILED_LOGIN"
  val SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN"
  
  val SUCCESSFUL_PURCHASE = "SUCCESSFUL_PURCHASE"
}
